### ISSUE TITLE
Allow user to add arbitrary values for fancy multi select

### ISSUE THREAD

**Issue by kalaschnik** [mxkaske/mxkaske.dev#13]
This is likely a cmdk issue; yet, I was wondering if it's possible to allow a user to enter arbitrary values for the fancy multi select component.

**Comment by kalaschnik** [comment]
Found it on my own

**Comment by noxify** [comment]
what was the solution @kalaschnik ?

**Comment by kalaschnik** [comment]
I stripped away a lot of stuff that is not needed for this purpose. I also put the user-provided values into the router. Here is a demo:

https://codesandbox.io/p/devbox/amazing-feather-4y53k7
