### ISSUE TITLE
Breaking Changes Introduces in cmdk 1.0.0

### ISSUE THREAD

**Issue by srshah27** [mxkaske/mxkaske.dev#16]
Right now if you try to replicate this multi-select, cmdk v1.0.0 will be installed, which has majorly 2 [breaking changes](https://github.com/pacocoursey/cmdk/releases/tag/v1.0.0) affecting this project.

- Command.List is now required
- Update [aria-disabled] and [aria-selected] CSS selectors

Using shadcn it is fairly simple:

- Wrap the `<CommandGroup>` with `<CommandList>` (using shadcn)
    - This will work but the drop down items will be greyed out
- Replace the `data-[disabled]` value with `data-[disabled='true']` thanks to [jhnguyen521](https://github.com/shadcn-ui/ui/issues/2944#issuecomment-1985153126)

**Comment by Qodestackr** [comment]
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

**Comment by MagisterUnivers** [comment]
`'use client'

import * as React from 'react'
import { X } from 'lucide-react'

import { Badge } from '@/components/ui/badge'
import {
  Command,
  CommandGroup,
  CommandItem,
  CommandList
} from '@/components/ui/command'
import { Command as CommandPrimitive } from 'cmdk'

type Framework = Record<'value' | 'label', string>

const FRAMEWORKS = [
  {
    value: 'next.js',
    label: 'Next.js'
  },
  {
    value: 'sveltekit',
    label: 'SvelteKit'
  },
  {
    value: 'nuxt.js',
    label: 'Nuxt.js'
  },
  {
    value: 'remix',
    label: 'Remix'
  },
  {
    value: 'astro',
    label: 'Astro'
  },
  {
    value: 'wordpress',
    label: 'WordPress'
  },
  {
    value: 'express.js',
    label: 'Express.js'
  },
  {
    value: 'nest.js',
    label: 'Nest.js'
  }
] satisfies Framework[]

export function MultiSelect (): React.ReactNode {
  const inputRef = React.useRef<HTMLInputElement>(null)
  const [open, setOpen] = React.useState(false)
  const [selected, setSelected] = React.useState<Framework[]>([FRAMEWORKS[7]])
  const [selectables, setIsSelectables] = React.useState(FRAMEWORKS.filter(framework => !selected.includes(framework)))
  const [inputValue, setInputValue] = React.useState('')

  const handleUnselect = React.useCallback((framework: Framework) => {
    setSelected(prev => prev.filter(s => s.value !== framework.value))
  }, [])

  const handleKeyDown = React.useCallback((e: React.KeyboardEvent<HTMLDivElement>) => {
    const input = inputRef.current
    if (input != null) {
      if (e.key === 'Delete' || e.key === 'Backspace') {
        if (input.value === '') {
          setSelected(prev => {
            const newSelected = [...prev]
            newSelected.pop()
            return newSelected
          })
        }
      }
      // This is not a default behaviour of the <input /> field
      if (e.key === 'Escape') {
        input.blur()
      }
    }
  }, [])

  React.useEffect(() => {
    setIsSelectables(FRAMEWORKS.filter(framework => !selected.some(s => s.value === framework.value)))
  }, [selected])

  // const selectables = FRAMEWORKS.filter(framework => !selected.includes(framework))
  // const selectables = FRAMEWORKS.filter(framework => !selected.some(s => s.value === framework.value))
  console.log(selectables, 'Selectables')

  return (
    <Command onKeyDown={handleKeyDown} className='overflow-visible bg-transparent'>
      <div
        className='group border border-input px-3 py-2 text-sm ring-offset-background rounded-md focus-within:ring-2 focus-within:ring-ring focus-within:ring-offset-2'
      >
        <div className='flex gap-1 flex-wrap'>
          {selected?.map((framework) => {
            return (
              <Badge key={framework.value} variant='secondary'>
                {framework.label}
                <button
                  className='ml-1 ring-offset-background rounded-full outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2'
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') {
                      handleUnselect(framework)
                    }
                  }}
                  onMouseDown={(e) => {
                    e.preventDefault()
                    e.stopPropagation()
                  }}
                  onClick={() => handleUnselect(framework)}
                >
                  <X className='h-3 w-3 text-muted-foreground hover:text-foreground' />
                </button>
              </Badge>
            )
          })}
          <CommandPrimitive.Input
            ref={inputRef}
            value={inputValue}
            onValueChange={(e) => setInputValue(e)}
            onBlur={() => setOpen(false)}
            onFocus={() => setOpen(true)}
            placeholder='Select frameworks...'
            className='ml-2 bg-transparent outline-none placeholder:text-muted-foreground flex-1'
          />
        </div>
      </div>
      <div className='relative mt-2'>
        {open && selectables?.length > 0
          ? (
            <div className='absolute w-full z-10 top-0 rounded-md border bg-popover text-popover-foreground shadow-md outline-none animate-in'>
              <CommandList>
                <CommandGroup className='h-full overflow-auto'>
                  {selectables?.map((framework) => {
                    return (
                      <CommandItem
                        key={framework.value}
                        onMouseDown={(e) => {
                          e.preventDefault()
                          e.stopPropagation()
                        }}
                        onSelect={(value) => {
                          setInputValue('')
                          setSelected(prev => [...prev, framework])
                        }}
                        className='cursor-pointer'
                      >
                        {framework.label}
                      </CommandItem>
                    )
                  })}
                </CommandGroup>
              </CommandList>
            </div>
            )
          : null}
      </div>
    </Command>
  )
}
`

Was TypeError: as guy wroted above, but with @srshah27  mention changes above, make some revisite to original code, make a lot of 'security - checks', and now i dont have typeError anymore.

**Comment by mxkaske** [comment]
Thanks @srshah27! I've bumped the library and pushed the changes.

The tricky part is to keep `<CommandList>` outside of ternary to avoid having the issue mentionned by @Qodestackr. It seems `cmdk` needs to have access to `listInnerRef` in any circumstances.

https://github.com/mxkaske/mxkaske.dev/pull/19/files#diff-340d27321ac0dbbc055ac58dcdb4c846c4701c831a8a65e7e134d7c338ca17b5R132-R157
